# Generated by Django 6.0.3 on 2026-04-03 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idempresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idproveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('idsede', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('ciudad', models.CharField(blank=True, max_length=15, null=True)),
                ('pais', models.CharField(blank=True, max_length=15, null=True)),
                ('idempresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('idinventario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Principal', 'Principal'), ('Respaldo', 'Respaldo')], max_length=10)),
                ('idempresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
                ('idproveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.proveedor')),
                ('idsede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sede')),
            ],
            options={
                'unique_together': {('idsede', 'idproveedor')},
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idevento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('causa', models.CharField(blank=True, max_length=50, null=True)),
                ('idproveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.proveedor')),
                ('idsede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sede')),
            ],
            options={
                'indexes': [models.Index(fields=['idsede'], name='idx_eventos_sede'), models.Index(fields=['idproveedor'], name='idx_eventos_proveedor')],
            },
        ),
    ]
