# Generated by Django 6.0.4 on 2026-04-15 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_empresa_options_alter_evento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_disponibilidad', models.FloatField(default=0.99, help_text='Ejemplo: 0.99 para 99%')),
                ('minutos_dia', models.IntegerField(default=1440, help_text='Minutos en un día (24h = 1440)')),
            ],
            options={
                'verbose_name': 'Configuración Global',
                'verbose_name_plural': 'Configuración Global',
            },
        ),
        migrations.CreateModel(
            name='TipoFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Falla',
                'verbose_name_plural': 'Tipos de Fallas',
            },
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='idempresa',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='idproveedor',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='idsede',
        ),
        migrations.RemoveIndex(
            model_name='evento',
            name='idx_eventos_proveedor',
        ),
        migrations.AddField(
            model_name='evento',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='ticket_soporte',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de Ticket'),
        ),
        migrations.AddField(
            model_name='sede',
            name='canal_primario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedes_primario', to='app.proveedor', verbose_name='Canal Primario'),
        ),
        migrations.AddField(
            model_name='sede',
            name='canal_secundario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedes_secundario', to='app.proveedor', verbose_name='Canal Secundario'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='idproveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.proveedor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='ciudad',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sede',
            name='pais',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='idtipo_falla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tipofalla', verbose_name='Causa de Falla'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['fecha_inicio'], name='idx_eventos_fecha'),
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='causa',
        ),
    ]
