# Generated by Django 6.0.4 on 2026-04-15 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_configuracionglobal_tipofalla_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='ticket_soporte',
        ),
    ]
