# Generated by Django 6.0.4 on 2026-04-15 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_evento_ticket_soporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='rol',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='duracion_horas',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='Horas'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='duracion_minutos',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Minutos'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateTimeField(verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='idproveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='idsede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sede', verbose_name='Sede'),
        ),
    ]
