# Generated by Django 6.0.4 on 2026-04-23 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_evento_rol_alter_evento_duracion_horas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='canal_mpls',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedes_mpls', to='app.proveedor', verbose_name='Canal MPLS'),
        ),
    ]
