# Generated by Django 6.0.4 on 2026-04-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_sede_canal_mpls'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlaceDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Ir al Dashboard KPI',
                'verbose_name_plural': 'Ir al Dashboard KPI',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.sede',),
        ),
        migrations.AlterField(
            model_name='evento',
            name='rol',
            field=models.CharField(blank=True, choices=[('Principal', 'Principal'), ('Respaldo', 'Respaldo'), ('MPLS', 'MPLS')], max_length=20, null=True, verbose_name='Rol'),
        ),
    ]
