# Generated by Django 6.0.4 on 2026-05-04 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_enlacedashboard_alter_evento_rol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnlaceDashboard',
        ),
        migrations.RemoveIndex(
            model_name='evento',
            name='idx_eventos_sede',
        ),
        migrations.RemoveIndex(
            model_name='evento',
            name='idx_eventos_fecha',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='comentarios',
            new_name='observaciones',
        ),
        migrations.AddField(
            model_name='evento',
            name='ticket_proveedor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='duracion_horas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='duracion_minutos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='idproveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.proveedor'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='idsede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sede'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='idtipo_falla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tipofalla'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='rol',
            field=models.CharField(blank=True, choices=[('Principal', 'Principal'), ('Respaldo', 'Respaldo'), ('MPLS', 'MPLS')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='EnlaceDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': ' Ver Dashboard Completo',
                'verbose_name_plural': ' Ver Dashboard Completo',
                'managed': False,
            },
        ),
    ]
