# Generated by Django 6.0.4 on 2026-05-04 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_enlacedashboard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='nodo_central_mpls',
            field=models.ForeignKey(blank=True, help_text='Si esta sede pierde MPLS cuando otra sede principal se cae, selecciona aquí la sede principal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sedes_hijas_mpls', to='app.sede', verbose_name='Nodo Padre MPLS (Topología Estrella)'),
        ),
    ]
